# single test suite, non-parallel build.
language: ruby

env:
  global:
    CC_TEST_REPORTER_ID=4d1c202579660ce52a244c95eaaf8f6d3ade1207340584c6257455a9fba79659

rvm:
  - 2.2.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle init
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT